### ISSUE TITLE
Deploy Fails in RakeFile

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/google-books#122]
```
#<Thread:0x00007f9dd91fef40@/Users/sul.amcollie/.rvm/gems/ruby-2.6.5/gems/sshkit-1.20.0/lib/sshkit/runners/parallel.rb:10 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	13: from /Users/sul.amcollie/.rvm/gems/ruby-2.6.5/gems/sshkit-1.20.0/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
	12: from /Users/sul.amcollie/.rvm/gems/ruby-2.6.5/gems/sshkit-1.20.0/lib/sshkit/backends/abstract.rb:31:in `run'
	11: from /Users/sul.amcollie/.rvm/gems/ruby-2.6.5/gems/sshkit-1.20.0/lib/sshkit/backends/abstract.rb:31:in `instance_exec'
	10: from /Users/sul.amcollie/.rvm/gems/ruby-2.6.5/gems/capistrano-rails-1.4.0/lib/capistrano/tasks/assets.rake:67:in `block (4 levels) in <top (required)>'
	 9: from /Users/sul.amcollie/.rvm/gems/ruby-2.6.5/gems/sshkit-1.20.0/lib/sshkit/backends/abstract.rb:92:in `within'
	 8: from /Users/sul.amcollie/.rvm/gems/ruby-2.6.5/gems/capistrano-rails-1.4.0/lib/capistrano/tasks/assets.rake:68:in `block (5 levels) in <top (required)>'
	 7: from /Users/sul.amcollie/.rvm/gems/ruby-2.6.5/gems/sshkit-1.20.0/lib/sshkit/backends/abstract.rb:100:in `with'
	 6: from /Users/sul.amcollie/.rvm/gems/ruby-2.6.5/gems/capistrano-rails-1.4.0/lib/capistrano/tasks/assets.rake:69:in `block (6 levels) in <top (required)>'
	 5: from /Users/sul.amcollie/.rvm/gems/ruby-2.6.5/gems/sshkit-1.20.0/lib/sshkit/backends/abstract.rb:80:in `execute'
	 4: from /Users/sul.amcollie/.rvm/gems/ruby-2.6.5/gems/sshkit-1.20.0/lib/sshkit/backends/abstract.rb:148:in `create_command_and_execute'
	 3: from /Users/sul.amcollie/.rvm/gems/ruby-2.6.5/gems/sshkit-1.20.0/lib/sshkit/backends/abstract.rb:148:in `tap'
	 2: from /Users/sul.amcollie/.rvm/gems/ruby-2.6.5/gems/sshkit-1.20.0/lib/sshkit/backends/abstract.rb:148:in `block in create_command_and_execute'
	 1: from /Users/sul.amcollie/.rvm/gems/ruby-2.6.5/gems/sshkit-1.20.0/lib/sshkit/backends/netssh.rb:170:in `execute_command'
/Users/sul.amcollie/.rvm/gems/ruby-2.6.5/gems/sshkit-1.20.0/lib/sshkit/command.rb:97:in `exit_status=': rake exit status: 1 (SSHKit::Command::Failed)
rake stdout: gem rubocop not available presumably b/c this is a production environment
gem rspec not available presumably b/c this is a production environment
rake stderr: Nothing written
```

**Comment by jcoyne** [comment]
I suspect this is same as #121

**Comment by aaron-collier** [comment]
It may be.

**Comment by mjgiarlo** [comment]
We think this is a duplicate. Closing.
