### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/google-books#271]
```
Started GET "/favicon.ico" for 127.0.0.1 at 2020-02-07 07:48:01 -0500
  
ActionController::RoutingError (No route matches [GET] "/favicon.ico"):
  
actionpack (6.0.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.2.1) lib/rails/rack/logger.rb:38:in `call_app'
railties (6.0.2.1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.2.1) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.2.1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.2.1) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.2.1) lib/rails/rack/logger.rb:26:in `call'
```

**Comment by justinlittman** [comment]
@astridu Would you be able to design a favicon for us? Super simple is just fine.

**Comment by justinlittman** [comment]
![rosette.ico](https://images.zenhubusercontent.com/5d8270f64def500001d12f23/6e900fe9-0a77-4fdf-a394-57422062d8b5)
